<a href="https://colab.research.google.com/github/muradhassen/Python_AI/blob/master/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
from numpy.random import randn
#Series
a = [1,2,3,4]
b = ['A' , 'B' , 'C' , 'D']
ck = pd.Series(a ,index=b)
ck

A    1
B    2
C    3
D    4
dtype: int64

In [9]:
import pandas as pd
import numpy as np
from numpy.random import randn
from google.colab import files
#dataFrame
dt1 = randn(5 , 4)
row = ['A' , 'B' , 'C' , 'D' , 'E']
col = ['P' , 'Q' , 'R' , 'S']
df = pd.DataFrame(dt1 , index=row , columns=col)
df

          P         Q         R         S
A -0.024343 -0.266164 -1.023507 -0.508072
B -0.516498 -0.168623 -0.206112 -0.072638
C  1.692071  0.805576  0.595995  1.304740
D  2.212280  1.029725 -1.660398  1.619386
E -0.570181  0.959301  0.503923 -1.000315

In [4]:
#import csv file
import pandas as pd
import numpy as np
from numpy.random import randn
from google.colab import files
df = pd.read_csv('ai_job_dataset.csv')
df.columns
df.loc[1]
df.loc[[0 , 5]]

,job_id,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name
0,AI00001,AI Research Scientist,90376,USD,SE,CT,China,M,China,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,1076,5.9,Smart Analytics
5,AI00006,AI Architect,123574,EUR,SE,CT,Germany,M,Germany,50,"Data Visualization, R, SQL, Linux",Associate,7,Healthcare,2024-08-31,2024-10-04,819,5.9,Neural Networks Co

In [21]:
#pull data outof tha dadaframe
import pandas as pd
import numpy as np
from numpy.random import randn
from google.colab import files
df = pd.read_csv('ai_job_dataset.csv')
# df.head() #fisrt 5 rows
# df.head(9) #first 9 rows
# df.tail() #last 5 rows
# df.tail(9) #last 9 rows
# df.info() #total information
# df.shape #rows and colums
# df.ndim  #dimension number
# df.dtypes  #all data type
# df.describe() #statistical information
df['company_name'].describe() #describe a spacific colums

0          Smart Analytics
1             TechCorp Inc
2          Autonomous Tech
3           Future Systems
4        Advanced Robotics
               ...
14995    Advanced Robotics
14996      Smart Analytics
14997       AI Innovations
14998      Smart Analytics
14999       AI Innovations
Name: company_name, Length: 15000, dtype: object

In [39]:
#count data in dataFrame
import pandas as pd
import numpy as np
from numpy.random import randn
from google.colab import files
df = pd.read_csv('ai_job_dataset.csv')
df['company_name'].value_counts()  #count distinct value -desindeing
df['company_name'].value_counts(ascending=True)  #count distinct value -aceending
df['company_name'].value_counts(dropna=False, ascending=True) #show null value aslo NaN
df['education_required'].value_counts(dropna=False, ascending=True , normalize=True) #show percentage
df['education_required'].value_counts()['PhD']
df['education_required'].value_counts()
df.groupby('education_required').count()
df.groupby('education_required').size()
# df.apply(pd.value_counts) #get a count of all colums across all colums

education_required
Associate    3785
Bachelor     3789
Master       3748
PhD          3678
dtype: int64